#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$AndroidSdk,
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
$CompileSdk = 36

function Fail {
    param([string]$Message)
    Write-Host ""
    Write-Host ("ERROR: " + $Message) -ForegroundColor Red
    exit 1
}

function Read-SdkFromLocalProperties {
    param([string]$FilePath)

    if (-not (Test-Path -LiteralPath $FilePath)) {
        return $null
    }

    try {
        foreach ($line in Get-Content -LiteralPath $FilePath) {
            if ($line -match '^\s*sdk\.dir\s*=\s*(.+?)\s*$') {
                $value = $Matches[1]
                $value = $value.Replace('\:', ':')
                $value = $value.Replace('\\', '\')
                if (Test-Path -LiteralPath $value) {
                    return (Resolve-Path -LiteralPath $value).Path
                }
            }
        }
    }
    catch {}

    return $null
}

function Test-AndroidSdk {
    param([string]$SdkPath)

    if ([string]::IsNullOrWhiteSpace($SdkPath)) {
        return $false
    }

    try {
        $resolved = (Resolve-Path -LiteralPath $SdkPath -ErrorAction Stop).Path
    }
    catch {
        return $false
    }

    $androidJar = Join-Path $resolved ("platforms\android-" + $CompileSdk + "\android.jar")
    return (Test-Path -LiteralPath $androidJar)
}

function Find-AndroidSdk {
    param(
        [string]$ExplicitAndroidSdk,
        [string]$LocalPropertiesPath
    )

    $items = New-Object System.Collections.Generic.List[string]

    if (-not [string]::IsNullOrWhiteSpace($ExplicitAndroidSdk)) {
        $items.Add($ExplicitAndroidSdk)
    }

    $fromLocal = Read-SdkFromLocalProperties -FilePath $LocalPropertiesPath
    if ($fromLocal) {
        $items.Add($fromLocal)
    }

    if ($env:ANDROID_SDK_ROOT) {
        $items.Add($env:ANDROID_SDK_ROOT)
    }

    if ($env:ANDROID_HOME) {
        $items.Add($env:ANDROID_HOME)
    }

    if ($env:LOCALAPPDATA) {
        $items.Add((Join-Path $env:LOCALAPPDATA "Android\Sdk"))
    }

    if ($env:USERPROFILE) {
        $items.Add((Join-Path $env:USERPROFILE "AppData\Local\Android\Sdk"))
    }

    foreach ($candidate in @($items | Where-Object { $_ } | Select-Object -Unique)) {
        if (Test-AndroidSdk -SdkPath $candidate) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }
    }

    return $null
}

function Write-LocalProperties {
    param(
        [string]$FilePath,
        [string]$SdkPath
    )

    $portablePath = $SdkPath.Replace('\', '/')
    Set-Content -LiteralPath $FilePath -Encoding ASCII -Value @(
        "# Auto-generated by Build-MemoBrainRelease.ps1",
        ("sdk.dir=" + $portablePath)
    )
}

if (-not [string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    $ProjectRoot = $PSScriptRoot
}
elseif ($MyInvocation.MyCommand.Path) {
    $ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
}
else {
    $ProjectRoot = (Get-Location).Path
}

$ProjectRoot = (Resolve-Path -LiteralPath $ProjectRoot).Path
$gradlew = Join-Path $ProjectRoot "gradlew.bat"
$signingSecrets = Join-Path $ProjectRoot "signing-secrets.properties"
$localProperties = Join-Path $ProjectRoot "local.properties"

Write-Host "MemoBrain Signed Release APK Builder v1.0.0" -ForegroundColor Green
Write-Host ("Project: " + $ProjectRoot)
Write-Host "Ads: WebView AdSense only (no native AdMob IDs required)"

if (-not (Test-Path -LiteralPath $gradlew)) {
    Fail "gradlew.bat was not found. Run git pull and try again."
}

if (-not (Test-Path -LiteralPath $signingSecrets)) {
    Fail "signing-secrets.properties was not found. Copy signing-secrets.properties.example and set the signing values."
}

$sdkPath = Find-AndroidSdk -ExplicitAndroidSdk $AndroidSdk -LocalPropertiesPath $localProperties
if (-not $sdkPath) {
    Fail ("Android SDK API " + $CompileSdk + " was not found. Install API " + $CompileSdk + " in Android Studio SDK Manager, or run with -AndroidSdk <path>.")
}

$env:ANDROID_SDK_ROOT = $sdkPath
$env:ANDROID_HOME = $sdkPath
Write-LocalProperties -FilePath $localProperties -SdkPath $sdkPath
Write-Host ("Android SDK: " + $sdkPath)

Push-Location $ProjectRoot
try {
    if ($Clean) {
        & $gradlew --no-daemon clean
        if ($LASTEXITCODE -ne 0) {
            Fail "Gradle clean failed."
        }
    }

    & $gradlew --no-daemon :app:assembleRelease --stacktrace
    if ($LASTEXITCODE -ne 0) {
        Fail "Release APK build failed."
    }

    $sourceApk = Join-Path $ProjectRoot "app\build\outputs\apk\release\app-release.apk"
    if (-not (Test-Path -LiteralPath $sourceApk)) {
        Fail ("Signed release APK was not found: " + $sourceApk)
    }

    $outputDir = Join-Path $ProjectRoot "output"
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

    $outputApk = Join-Path $outputDir "MemoBrain-v1.3.0-release.apk"
    Copy-Item -LiteralPath $sourceApk -Destination $outputApk -Force

    $hash = (Get-FileHash -LiteralPath $outputApk -Algorithm SHA256).Hash.ToLowerInvariant()
    $shaFile = Join-Path $outputDir "SHA256SUMS.txt"
    Set-Content -LiteralPath $shaFile -Encoding ASCII -Value ("{0}  {1}" -f $hash, (Split-Path -Leaf $outputApk))

    $sdkCandidates = @($sdkPath)
    if ($env:ANDROID_SDK_ROOT) {
        $sdkCandidates += $env:ANDROID_SDK_ROOT
    }
    if ($env:ANDROID_HOME) {
        $sdkCandidates += $env:ANDROID_HOME
    }

    $apksigner = $null
    foreach ($sdk in ($sdkCandidates | Select-Object -Unique)) {
        if (-not (Test-Path -LiteralPath $sdk)) {
            continue
        }

        $buildTools = Join-Path $sdk "build-tools"
        if (-not (Test-Path -LiteralPath $buildTools)) {
            continue
        }

        $candidate = Get-ChildItem -LiteralPath $buildTools -Directory -ErrorAction SilentlyContinue |
            Sort-Object Name -Descending |
            ForEach-Object { Join-Path $_.FullName "apksigner.bat" } |
            Where-Object { Test-Path -LiteralPath $_ } |
            Select-Object -First 1

        if ($candidate) {
            $apksigner = $candidate
            break
        }
    }

    if ($apksigner) {
        Write-Host ""
        Write-Host "=== APK signature verification ===" -ForegroundColor Cyan
        & $apksigner verify --verbose --print-certs $outputApk
        if ($LASTEXITCODE -ne 0) {
            Fail "APK signature verification failed."
        }
    }
    else {
        Write-Warning "apksigner.bat was not found. Automatic signature verification was skipped."
    }

    Write-Host ""
    Write-Host "Signed release APK created successfully." -ForegroundColor Green
    Write-Host ("APK    : " + $outputApk)
    Write-Host ("SHA256 : " + $hash)
    Write-Host ("SUMS   : " + $shaFile)
}
finally {
    Pop-Location
}
